from soccer.models import SoccerGame


TEST_GAMES_SOCCER = [
    SoccerGame(
        away="MUN",
        home="LIV",
        status="Scheduled",
        start_time="10:00",
        date="Sep 14",
        away_score=0,
        home_score=0,
        away_wins=4,
        away_draws=1,
        away_losses=1,
        home_wins=5,
        home_draws=0,
        home_losses=1,
        league_id="eng.1",
        league_name="Premier League",
        league_short="EPL",
        event_id="test-epl-1",
    ),
    SoccerGame(
        away="RMA",
        home="BAR",
        status="Live",
        start_time="",
        date="",
        away_score=1,
        home_score=1,
        period=2,
        clock="67",
        league_id="esp.1",
        league_name="La Liga",
        league_short="LIGA",
        event_id="test-liga-1",
    ),
    SoccerGame(
        away="MCI",
        home="BAY",
        status="Halftime",
        start_time="",
        date="",
        away_score=2,
        home_score=0,
        period=1,
        league_id="uefa.champions",
        league_name="Champions League",
        league_short="UCL",
        event_id="test-ucl-1",
    ),
    SoccerGame(
        away="LAFC",
        home="ATL",
        status="Final",
        start_time="",
        date="",
        away_score=3,
        home_score=2,
        period=2,
        league_id="usa.1",
        league_name="MLS",
        league_short="MLS",
        event_id="test-mls-1",
    ),
]
